/**
 * Per-sample descriptions shown under each row in the sample list, keyed by
 * screen key. Descriptions mirror the official ArcGIS Maps SDK samples; entries
 * for this app’s consolidated / renamed screens are adapted. Generated data.
 */
export const SCREEN_DESCRIPTIONS: Partial<Record<string, string>> = {
  animategraphic: 'An `OrbitGeoElementCameraController` follows a graphic while the graphic\'s position and rotation are animated.',
  annotationsublayer: 'Use annotation sublayers to gain finer control of annotation layer subtypes.',
  arcadeexpression: 'Query features on a map using an Arcade expression.',
  ardiagnostics:
    'Debug AR tracking and inspect all device motion sensors (accelerometer, gyroscope, magnetometer, device motion) live, with update rates.',
  arcollect: 'Tap on real-world objects to collect data.',
  arflyover: 'Use augmented reality (AR) to quickly explore a scene more naturally than you could with a touch or mouse interface.',
  arhidden: 'Visualize hidden infrastructure in its real-world location using augmented reality.',
  arnavigate: 'Use a route displayed in the real world to navigate.',
  artabletop: 'Use augmented reality (AR) to pin a scene to a table or desk for easy exploration.',
  atmosphere: 'Changes the appearance of the atmosphere in a scene.',
  attachments: 'Add, delete, and download attachments for features from a service.',
  auth: 'Access a web map that is secured with ArcGIS token-based authentication.',
  background: 'Customize map view\'s background by changing its grid properties.',
  basemap: 'Change a map\'s basemap.',
  basemapgallery: 'Implement a basemap gallery that automatically retrieves the latest customization options from the basemap styles service.',
  basemapparams: 'Apply basemap style parameters customization for a basemap, such as displaying all labels in a specific language or displaying every label in their corresponding local language.',
  blendraster: 'Blend a hillshade with a raster by specifying the elevation data. The resulting raster looks similar to the original raster, but with some terrain shading, giving it a textured look.',
  bookmarks: 'Access and create bookmarks on a map.',
  branchversion: 'Create, query, and edit a specific server version using a service geodatabase.',
  buildingscenelayer: 'Add a layer to a local scene to visualize and interact with 3D building models developed using Building Information Modeling (BIM) tools.',
  callout: 'Show a callout with the latitude and longitude of user-tapped points.',
  cameraviewshed: 'Analyze the exploratory viewshed for a camera showing the visible and obstructed areas from an observer\'s vantage point.',
  closestfacility: 'Find routes from several locations to the respective closest facility.',
  closestfacilitymulti: 'Find a route to the closest facility from a location.',
  cluster: 'Display a web map with a point feature layer that has feature reduction enabled to aggregate points into clusters.',
  colormapraster: 'Apply a colormap renderer to a raster.',
  coordinates: 'Format coordinates in a variety of common notations.',
  creategdb: 'Create and share a mobile geodatabase.',
  customdictionary: 'Use a custom dictionary style created from a web style or local style file (.stylx) to symbolize features using a variety of attribute values.',
  customdynamicentity: 'Create a custom dynamic entity data source and display it using a dynamic entity layer.',
  distancecomposite: 'Change a graphic\'s symbol based on the camera\'s proximity to it.',
  distancemeasurement: 'Measure distances between two points in 3D.',
  dynamicentitylayer: 'Display data from an ArcGIS stream service using a dynamic entity layer.',
  edit: 'Create, update, and delete features to manage a feature layer.',
  enc: 'Display and configure electronic navigational charts per ENC specification.',
  error: 'Demonstrates how the module surfaces a stable, typed error from a deliberately failing load.',
  extrudedfeatures: 'Extrude features based on their attributes.',
  extrudedgraphics: 'Extrude graphics based on an attribute value.',
  fcquery: 'Create a feature collection layer to show a query result from a service feature table.',
  featurecollection: 'Create a feature collection layer from a portal item.',
  featureform: 'Display and edit feature attributes using feature forms.',
  featurelinkedannotation: 'Edit feature attributes which are linked to annotations through an expression.',
  featurerenderingmodemap: 'Render features statically or dynamically by setting the feature layer rendering mode.',
  featurerequestmode: 'Use different feature request modes to populate the map from a service feature table.',
  filterbuildingscenelayer: 'Explore details of a building scene by using filters and sublayer visibility.',
  filterfeatures: 'Filter 3D scene features out of a given geometry with a polygon filter.',
  floors: 'Display and browse through building floors from a floor-aware web map.',
  gdbtransaction: 'Use transactions to manage how changes are committed to a geodatabase.',
  geocode: 'Find the location for an address, or places of interest near a location or within a specific area.',
  geodatabase: 'Generate a local geodatabase from a feature service, edit it, and sync the changes back to the service.',
  geodesic: 'Calculate a geodesic path between two points and measure its distance.',
  geodesicsectorellipse: 'Create and display geodesic sectors and ellipses.',
  geoelementlineofsight: 'Show an exploratory line of sight between two moving objects.',
  geoelementviewshed: 'Analyze the exploratory viewshed for an object (GeoElement) in a scene.',
  geometryeditor: 'Use the Geometry Editor to edit a geometry and align it to existing geometries on a map.',
  geometryops: 'Perform geometry operations — buffer, clip, cut, convex hull, and spatial relationships.',
  geometryrefine: 'Simplify a self-intersecting polygon, and densify or generalize a geometry.',
  geometrytypes: 'Use a symbol to display a geometry on a map.',
  geotriggers: 'Create a notification every time a given location data source has entered and/or exited a set of features or graphics.',
  gpviewshed: 'Calculate a viewshed using a geoprocessing service, in this case showing what parts of a landscape are visible from points on mountainous terrain.',
  graphics: 'Use a symbol style to display a graphic on a graphics overlay.',
  grid: 'Display and customize coordinate system grids, including Latitude/Longitude, MGRS, UTM, and USNG, on a map view or scene view.',
  grouplayer: 'Group a collection of layers together and toggle their visibility as a group.',
  hotspots: 'Use a geoprocessing service and a set of features to identify statistically significant hot spots and cold spots.',
  identify: 'Identify features in all layers in a map.',
  identifyrastercell: 'Get the cell value of a local raster at the tapped location and display the result in a callout.',
  identifywms: 'Identify features in a WMS layer and display the associated popup content.',
  imageoverlay: 'Animate a series of images with an image overlay.',
  indoorpositioning: 'Show your device\'s real-time location while inside a building by using signals from indoor positioning beacons.',
  integratedmesh: 'View an integrated mesh layer from a scene service.',
  interactiveviewshed: 'Perform an interactive viewshed analysis to determine visible and non-visible areas from a given observer position.',
  iwaauth: 'Connect to an IWA secured Portal and search for maps.',
  kmlcontents: 'List the contents of a KML file.',
  kmlgroundoverlay: 'Edit the values of a KML ground overlay.',
  kmlidentify: 'Show a callout with formatted content for a KML feature.',
  kmlmultitrack: 'Create, save, and preview a KML multi-track captured from a location data source.',
  kmlnetworklink: 'Display a file with a KML network link, including displaying any network link control messages at launch.',
  kmlsave: 'Construct a KML document and save it as a KMZ file.',
  kmltour: 'Play tours in KML files.',
  labels: 'Display custom labels on a feature layer.',
  labels3d: 'Display custom labels in a 3D scene.',
  layers: 'Display feature layers from various data sources.',
  layertypes: 'Add and compare common 2D layer types: tiled, web-tiled, WMS, WMTS, WFS, OpenStreetMap, vector-tiled, map image, and raster.',
  lighting: 'Show realistic lighting and shadows for a given time of day.',
  lineofsight: 'Perform an exploratory line of sight analysis between two points in real time.',
  lineofsightmap: 'Perform a line of sight analysis in a map view between fixed observer and target positions.',
  listversions: 'Connect to a service and list versions of the geodatabase.',
  localscene: 'Display a local scene with a topographic surface and 3D scene layer clipped to a local area.',
  location: 'Show your current position on the map, as well as switch between different types of auto-pan modes.',
  manageoperationallayers: 'Add, remove, and reorder operational layers in a map.',
  mapalgebra: 'Apply map algebra to an elevation raster to floor, mask, and categorize the elevation values into discrete integer-based categories.',
  mapimagesublayer: 'Find features in a sublayer based on attributes and location.',
  matchviewpoint: 'Keep the viewpoints of two views, for example, a map view and a scene view, synchronized with each other.',
  mobilescenepackage: 'Opens and displays a scene from a Mobile Scene Package (.mspk).',
  mobilestylesymbol: 'Combine multiple symbols from a mobile style file into a single symbol.',
  monitorstatus: 'Monitor the map\'s draw status and each layer\'s view state as it loads.',
  mosaicraster: 'Apply mosaic rule to a mosaic dataset of rasters.',
  navigate: 'Use a routing service to navigate between two points.',
  navigatereroute: 'Navigate between two points and dynamically recalculate an alternate route when the original route is unavailable.',
  nmea: 'Parse NMEA sentences and use the results to show device location on the map.',
  offline: 'Take a web map offline.',
  ogccql: 'Query data from an OGC API feature service using CQL filters.',
  orbitcamera: 'Fix the camera to point at and rotate around a target object.',
  overview: 'Include an overview or inset map as an additional map view to show the wider context of the primary view.',
  pkiauth: 'Access secured portals using a certificate.',
  pointcloud: 'Display local 3D point cloud data.',
  pointscenelayer: 'View a point scene layer from a scene service.',
  popup: 'Show a predefined popup from a web map.',
  query: 'Find features in a feature table which match an SQL query.',
  querydepth: 'Filter features by a definition expression, select them, and query their count and extent.',
  querydynamicentities: 'Find dynamic entities from a data source that match a query.',
  querystats: 'Query a table to get aggregated statistics back for a specific field.',
  querytimeextent: 'Query data using a time extent.',
  rasterelevation: 'Set the terrain surface with elevation described by a raster file.',
  rasterfunctionservice: 'Load a raster from a service, then apply a function to it.',
  rasterrenderingrule: 'Display a raster on a map and apply different rendering rules to that raster.',
  related: 'List features related to the selected feature.',
  remount: 'Mount and unmount the native map view to verify it disposes and re-creates cleanly.',
  renderer: 'Apply simple, unique-value, and class-breaks renderers to a feature layer.',
  reticleeditor: 'Use the Programmatic Reticle Tool to edit and create geometries with programmatic operations to facilitate customized workflows such as those using buttons rather than tap interactions.',
  rgbraster: 'Apply an RGB renderer to a raster layer to enhance feature visibility.',
  rotation: 'Rotate a map.',
  route: 'Display directions for a route between two points.',
  routebarriers: 'Find a route that reaches all stops without crossing any barriers.',
  routedisplay: 'Display a route layer and its directions using feature collection.',
  routenetwork: 'Solve a route on-the-fly using offline data.',
  scalebar: 'Add a scale bar to visually gauge distances on a map.',
  scaleextent: 'Set a map\'s maximum extent, minimum/maximum scale, and reference scale.',
  scene: 'Display a scene with a terrain surface and some imagery.',
  sceneenvironment: 'Configure the environment settings in a local scene to change the lighting conditions and background appearance.',
  scenelayerrenderer: 'Change the appearance of a 3D object scene layer with different renderers.',
  sceneorientation: 'Update the orientation of a graphic using expressions based on its attributes.',
  scenerenderingmode: 'Render features in a scene statically or dynamically by setting the feature layer rendering mode.',
  sceneselection: 'Identify features in a scene to select.',
  sceneservice: 'Display an ArcGIS scene layer from a URL.',
  scenesymbol: 'Show various kinds of 3D symbols in a scene.',
  screenshot: 'Take a screenshot of the map.',
  searchwebmap: 'Find web map portal items by using a search term.',
  servicearea: 'Find the service area within a network from a given point.',
  serviceareamulti: 'Find the service areas of several facilities from a feature service.',
  servicebrowser: 'Browse the layers or collections of an OGC service (WMS, WFS, or OGC API - Features).',
  shapefilemetadata: 'Read a shapefile and display its metadata.',
  shapefilesymbology: 'Display a shapefile with custom symbology.',
  spatialref: 'Specify a map\'s spatial reference.',
  stylegraphicsrenderer: 'A renderer allows you to change the style of all graphics in a graphics overlay by referencing a single symbol style. A renderer will only affect graphics that do not specify their own symbol style.',
  sublayerclassbreaks: 'Apply a renderer to a sublayer.',
  subtypesublayer: 'Display a composite layer of all the subtype values in a feature class.',
  surfaceconstraint: 'See through terrain in a scene and move the camera underground.',
  surfaceelevation: 'Get the elevation for a given point on a surface in a scene.',
  surfaceplacement: 'Position graphics relative to a surface using different surface placement modes.',
  terrainexaggeration: 'Vertically exaggerate terrain in a scene.',
  tiledbasemap: 'Load an offline copy of a tiled map service as a basemap.',
  tilepackageelevation: 'Set the terrain surface with elevation described by a local tile package.',
  tiles3d: 'Add a layer to visualize 3D tiles data that conforms to the OGC 3D Tiles specification.',
  timeoffset: 'Display a time-enabled feature layer with a time offset.',
  transformations: 'Project a point from one coordinate system to another using a specific transformation step.',
  unassociations: 'Create graphics for utility associations in a utility network.',
  uncontainer: 'A utility network container allows a dense collection of features to be represented by a single feature, which can be used to reduce map clutter.',
  unisolation: 'Run a filtered trace to locate operable features that will isolate an area from the flow of network resources.',
  unloadreport: 'Create a simple electric distribution report that displays the count of customers and total load per phase by tracing downstream from a given point.',
  unsnap: 'Use the Geometry Editor to edit geometries using utility network connectivity rules.',
  unsubnetwork: 'Get a server-defined trace configuration for a given tier and modify its traversability scope, add new condition barriers, and control what is included in the subnetwork trace result.',
  untrace: 'Discover connected features in a utility network using connected, subnetwork, upstream, and downstream traces.',
  unvalidate: 'Demonstrates the workflow of getting the network state and validating the topology of a utility network.',
  updaterelated: 'Update related features in an online feature service.',
  vectortiles: 'Download tiles from an online vector tile service.',
  viewpoint: 'Set the map view to a new viewpoint.',
  viewshed: 'Perform an exploratory viewshed analysis from a defined vantage point.',
  vtlcustomstyle: 'Load an ArcGIS vector tiled layers using custom styles.',
  webmap: 'Display a web map.',
  webscene: 'Open a web scene from a portal item.',
  wfsxmlquery: 'Load a WFS feature table using an XML query.',
  wmsstyle: 'Change the style of a Web Map Service (WMS) layer.',
};
